### ISSUE TITLE
[Bug][GenerationLogic] Index was out of range. Must be non-negative and less than the size of the collection.Parameter name: startIndex

### ISSUE THREAD

**Issue by sathukorale** [sathukorale/C-PlantUML-Class-Diagram-Generator#4]
We are facing this issue `Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex` when trying to use the app. The following is the corresponding stack trace.

```
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at System.String.IndexOf(String value, Int32 startIndex, StringComparison comparisonType)
   at PlantUMLCodeGeneratorGUI.Macros.Process(String content) in D:\documents\C-PlantUML-Class-Diagram-Generator\PlantUMLCodeGeneratorGUI\Class.cs:line 735
   at PlantUMLCodeGeneratorGUI.Processor.Process(String fileContent, Settings settings, Namespace& defaultNamespace) in D:\documents\C-PlantUML-Class-Diagram-Generator\PlantUMLCodeGeneratorGUI\Class.cs:line 796
   at PlantUMLCodeGeneratorGUI.frmMain.<btnGenerate_Click>b__5_0(Object o) in D:\documents\C-PlantUML-Class-Diagram-Generator\PlantUMLCodeGeneratorGUI\frmMain.cs:line 77
```

**Comment by sathukorale** [comment]
Apparently the directory didn't have any files, thus an empty string was provided sent to the processing logic. This issue was fixed by resolving this situation. The fix commit is available at, fe8a9a245b548c13daede9e9214af9a54b1b1196.
