### ISSUE TITLE
[Bug][GenerationLogic] Length cannot be less than zero.Parameter name: length

### ISSUE THREAD

**Issue by dingysh2022** [sathukorale/C-PlantUML-Class-Diagram-Generator#7]
We are facing this issue `Length cannot be less than zero.
Parameter name: length` when trying to use the app. The following is the corresponding stack trace.

```
   at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at PlantUMLCodeGeneratorGUI.Class.Set(String classContent)
   at PlantUMLCodeGeneratorGUI.Namespace.ProcessFullContent(String fullContent)
   at PlantUMLCodeGeneratorGUI.Namespace.Set(String namespaceContent)
   at PlantUMLCodeGeneratorGUI.Namespace.Set(String namespaceContent)
   at PlantUMLCodeGeneratorGUI.Namespace.Set(String namespaceContent)
   at PlantUMLCodeGeneratorGUI.Namespace.Set(String namespaceContent)
   at PlantUMLCodeGeneratorGUI.Processor.Process(String fileContent, Settings settings, Namespace& defaultNamespace)
   at PlantUMLCodeGeneratorGUI.frmMain.<btnGenerate_Click>b__5_0(Object o)
```

**Comment by sathukorale** [comment]
@dingysh2022 If you dont mind, can you please share the code that recreates this. It doesn't have to be the exact same code, perhaps a trimmed version.
